OCR

diff --git a/.local/bin/ocr b/.local/bin/ocr
--- a/.local/bin/ocr
+++ b/.local/bin/ocr
@@ -1,4 +1,6 @@
-#!/usr/bin/env bash
+#!/bin/env bash
+
+[ -z "$1" ] && printf "Error: You need to provide a language.\nUsage: %s [language]\nTo specify multiple languages, use a '+' delimiter (not recommended).\n\n" "$0" && tesseract --list-langs && exit 1
 
 TEXT_FILE="/tmp/ocr.txt"
 IMAGE_FILE="/tmp/ocr.png"
@@ -7,7 +9,7 @@ IMAGE_FILE="/tmp/ocr.png"
 dependencies=(tesseract maim notify-send xclip)
 for dependency in "${dependencies[@]}"; do
     type -p "$dependency" &>/dev/null || {
-        notify-send "ocr" "Could not find '${dependency}', is it installed?"
+        notify-send "OCR" "Could not find '${dependency}', is it installed?"
         echo "Could not find '${dependency}', is it installed?"
         exit 1
     }
@@ -22,10 +24,13 @@ STATUS=$?
 # If the user pressed the escape key or did something to terminate the proccess taking a screenshot, then just exit
 [ $STATUS -ne 0 ] && exit 1
 
-# Specify language(s) to use
-LANG=kor
-
-tesseract --oem 1 --psm 6 -l "$LANG" -c preserve_interword_spaces=1 "$IMAGE_FILE" "${TEXT_FILE//\.txt/}" 2> /dev/null
+case "$1" in
+	kor) tesseract --oem 1 --psm 6 -l "$1" -c preserve_interword_spaces=1 "$IMAGE_FILE" "${TEXT_FILE//\.txt/}" 2> /dev/null ;;
+	chi_sim) tesseract --oem 1 --psm 6 -l "$1" -c preserve_interword_spaces=1 "$IMAGE_FILE" "${TEXT_FILE//\.txt/}" 2> /dev/null ;;
+	chi_tra) tesseract --oem 1 --psm 6 -l "$1" -c preserve_interword_spaces=1 "$IMAGE_FILE" "${TEXT_FILE//\.txt/}" 2> /dev/null ;;
+	eng) tesseract -l "$1" "$IMAGE_FILE" "${TEXT_FILE//\.txt/}" 2> /dev/null ;;
+	*) tesseract --oem 1 --psm 6 -l "$1" -c preserve_interword_spaces=1 "$IMAGE_FILE" "${TEXT_FILE//\.txt/}" 2> /dev/null ;;
+esac
 
 # Remove the new page character.
 sed -i 's/\x0c//' "$TEXT_FILE"
@@ -33,7 +38,7 @@ sed -i 's/\x0c//' "$TEXT_FILE"
 # Check if the text was detected by checking number of lines in the file
 NUM_LINES=$(wc -l < $TEXT_FILE)
 if [ "$NUM_LINES" -eq 0 ]; then
-    notify-send "ocr" "no text was detected"
+    notify-send "OCR" "no text was detected"
     exit 1
 fi
 
